#TetrisGameSettingsConfig
#Fri Oct 09 15:41:44 KST 2026
bgmVolume=60
displayMode=\uC804\uCCB4 \uD654\uBA74
fxVolume=83
masterVolume=63
p1Hard=SPACE
p1Left=LEFT
p1Right=RIGHT
p1Rotation=L
p1Soft=DOWN
p2Hard=W
p2Left=A
p2Right=D
p2Rotation=V
p2Soft=S
resolution=1920 x 1080
